DISCOURSE_API_KEY = 'YOUR_DISCOURSE_API_KEY'
DISCOURSE_API_USERNAME = 'YOUR_DISCOURSE_USERNAME'
DISCOURSE_BASE_URL = "YOUR_DISCOURSE_BASE_URL"
DISCOURSE_CLIENT_ID = "YOUR_DISCOURSE_CLIENT_ID"

OPENAI_API_KEY = 'YOUR_OPENAI_API_KEY'
OPENAI_MODEL = 'YOUR_OPENAI_MODEL'
DEEPSEEK_URL = 'YOUR_DEEPSEEK_URL'

API_KEY = 'YOUR_API_KEY'
MODEL = 'YOUR_MODEL'
URL = 'YOUR_URL'

GOOD_EXAMPLE = '''
good example from shuiyuan
'''

BAD_EXAMPLE = '''
bad example from shuiyuan
'''
